# Generated by Django 6.0.3 on 2026-03-23 10:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите своё имя",
                        max_length=30,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Введите свою фамилию",
                        max_length=30,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Введите свой никнейм",
                        max_length=50,
                        unique=True,
                        verbose_name="Никнейм",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Введите свою электронную почту",
                        max_length=50,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата создания аккаунта"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        help_text="Загрузите свой аватар", upload_to="ad/"
                    ),
                ),
                (
                    "area_of_residence",
                    models.CharField(
                        choices=[
                            ("ce", "Центральный"),
                            ("zh", "Железнодорожный"),
                            ("za", "Заельцовский"),
                            ("ka", "Калининский"),
                            ("ki", "Кировский"),
                            ("le", "Ленинский"),
                            ("oc", "Октябрьский"),
                            ("pe", "Первомайский"),
                            ("so", "Советский"),
                            ("dz", "Дзержинский"),
                        ],
                        help_text="Выберете район проживания",
                        verbose_name="Район проживания",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
