# Generated by Django 6.0.3 on 2026-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscription",
            field=models.BooleanField(
                default=False, verbose_name="Признак платной подписки"
            ),
        ),
    ]
