# Generated by Django 6.0.3 on 2026-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="area_of_residence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ce", "Центральный"),
                    ("zh", "Железнодорожный"),
                    ("za", "Заельцовский"),
                    ("ka", "Калининский"),
                    ("ki", "Кировский"),
                    ("le", "Ленинский"),
                    ("oc", "Октябрьский"),
                    ("pe", "Первомайский"),
                    ("so", "Советский"),
                    ("dz", "Дзержинский"),
                ],
                help_text="Выберете район проживания",
                null=True,
                verbose_name="Район проживания",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите свой аватар",
                null=True,
                upload_to="ad/",
            ),
        ),
    ]
