# Generated by Django 6.0.3 on 2026-03-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите названия объявления",
                        max_length=100,
                        verbose_name="Название объявления",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание объявления",
                        verbose_name="Описание объявления",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        upload_to="", verbose_name="Фотография объявления"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(verbose_name="Дата создания объявления"),
                ),
                ("phone_number", models.IntegerField(verbose_name="Номер телефона")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
