# Generated by Django 6.0.3 on 2026-03-29 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите названия объявления",
                        max_length=100,
                        verbose_name="Название объявления",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание объявления",
                        verbose_name="Описание объявления",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Фотография объявления",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания объявления"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=200, verbose_name="Номер телефона"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Признак премии"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
