# Generated by Django 6.0.3 on 2026-03-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"verbose_name": "Объявление", "verbose_name_plural": "Объявления"},
        ),
        migrations.AlterField(
            model_name="ad",
            name="date_created",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата создания объявления"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Фотография объявления",
            ),
        ),
    ]
