# Generated by Django 6.0.3 on 2026-03-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0002_alter_ad_options_alter_ad_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="user",
        ),
    ]
