# Generated by Django 6.0.3 on 2026-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0004_ad_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="phone_number",
            field=models.CharField(max_length=200, verbose_name="Номер телефона"),
        ),
    ]
