# Generated by Django 6.0.3 on 2026-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0005_alter_ad_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Премиум объявления"),
        ),
    ]
